ports:
- port: 4000
  onOpen: open-browser
- port: 4001
  onOpen: open-browser
- port: 4200
  onOpen: open-browser
# start up tasks
tasks:
- init: npm i -g @angular/cli
- command: cd server && npm install && npm run start:schema
- command: cd front && npm install && npm start

vscode:
  extensions:
    - cyrilletuzi.angular-schematics@2.2.2:jo/1thOzPLSapDisE7KHVw==
    - ms-vscode.vscode-typescript-tslint-plugin@1.2.3:MioHhlbqHKgivweg8MqHrA==
    - apollographql.vscode-apollo@1.12.1:0Ub6H46dWhAlGY8zWMaZBw==